#!/bin/sh
pyfiles=$(git diff --cached --name-only --diff-filter=ACM | grep '.py$')
for pf in $pyfiles; do

    if !($(black --check $pf)); then
        echo $pf
        black $pf
        echo "  formatted: $PWD/$pf"
        git add $pf
    fi
done
exit 0
