
name: 2020-Object-Detection-In-Aerial-Images
channels:
    - conda-forge
    - defaults
dependencies:
    - python=3.7.*
    - tensorflow-estimator=2.1.*
    - tensorflow=2.1.*
    - pandas
    - opencv
    - matplotlib
    - jupyterlab
    - scikit-image
    - gdown
    - imgaug
    - albumentations