# Make sure you update env_requirements.txt after updating environment.yml
# To update env_requirements.txt run 'conda env export > env_requirements.txt'
# Make sure your environment is active while doing this
name: 2020-Object-Detection-In-Aerial-Images
dependencies:
    - tensorflow=2.1.*
    - pandas
    - opencv
    - matplotlib
    - jupyterlab
