
name: 2020-Object-Detection-In-Aerial-Images
channels:
    - conda-forge
    - defaults
dependencies:
    - python=3.8.*
    - tensorflow=2.1.*
    - pandas
    - opencv
    - matplotlib
    - jupyterlab
    - gdown
